theme: minima
title: Just A Blog
author: Quesias
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a blog on the web.

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Quesias # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
